name: Chrome Extension Publish

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  chrome-publish:
    runs-on: ubuntu-latest
    environment: chrome-publish
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run release

      - name: Check if version has been updated
        id: version_change
        uses: EndBug/version-check@v1

      - name: Chrome Extension upload & publish
        if: steps.version_change.outputs.changed == 'true'
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: lbbbenibppgfmakcjpdchgdkjfeipndb
          client-id: 697242455057-i7c4ej57piivmio3os5216g4sefg6cdp.apps.googleusercontent.com
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name:
            releases/usos-srednia-${{
            steps.version_change.outputs.version_change }}.zip
          publish: true
