name: Chrome Extension Publish

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  has-changed:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_change.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check if version has been updated
        id: version_change
        uses: EndBug/version-check@v1

      - name: Early exit if version didn't change
        if: steps.version_change.outputs.changed != 'true'
        run: exit 1

  create-github-release-draft:
    runs-on: ubuntu-latest
    needs: has-changed
    outputs:
      id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ needs.has-changed.outputs.version }}
          release_name: ${{ needs.has-changed.outputs.version }}
          draft: true
          prerelease: false

  chrome-publish:
    runs-on: ubuntu-latest
    needs: ['has-changed', 'create-github-release-draft']
    environment: chrome-publish
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run release

      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: lbbbenibppgfmakcjpdchgdkjfeipndb
          client-id: 697242455057-i7c4ej57piivmio3os5216g4sefg6cdp.apps.googleusercontent.com
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name:
            releases/usos-srednia-${{ needs.has-changed.outputs.version  }}.zip
          publish: true

      - name: Upload to github releases
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url:
            ${{ needs.create-github-release-draft.outputs.upload_url  }}
          asset_path:
            releases/usos-srednia-${{ needs.has-changed.outputs.version  }}.zip
          asset_name:
            usos-srednia-chrome-${{ needs.has-changed.outputs.version  }}.zip
          asset_content_type: application/zip

  firefox-publish:
    runs-on: ubuntu-latest
    needs: ['has-changed', 'create-github-release-draft']
    environment: firefox-publish
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Change manifest to V2
        # Firefox doesn't support manifest V2
        run:
          echo "`jq '.manifest_version = 2' src/manifest.json`" >
          src/manifest.json

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run release

      - name: Upload to firefox addons
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{7738ac86-b5b2-4372-bc2b-1c371631bd73}'
          xpi:
            releases/usos-srednia-${{ needs.has-changed.outputs.version  }}.zip
          manifest: dist/manifest.json
          api-key: user:16832256:680
          api-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Upload to github releases
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url:
            ${{ needs.create-github-release-draft.outputs.upload_url  }}
          asset_path:
            releases/usos-srednia-${{ needs.has-changed.outputs.version  }}.zip
          asset_name:
            usos-srednia-firefox-${{ needs.has-changed.outputs.version  }}.zip
          asset_content_type: application/zip

  github-release-publish:
    runs-on: ubuntu-latest
    needs:
      [
        'has-changed',
        'create-github-release-draft',
        'firefox-publish',
        'chrome-publish',
      ]
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          release_id: ${{ needs.create-github-release-draft.outputs.id }}
