name: Chrome Extension Publish

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  chrome-publish:
    runs-on: ubuntu-latest
    environment: chrome-publish
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check if version has been updated
        id: version_change
        uses: EndBug/version-check@v1

      - name: Early exit if version didn't change
        if: steps.version_change.outputs.changed != 'true'
        run: exit 1

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run release

      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: lbbbenibppgfmakcjpdchgdkjfeipndb
          client-id: 697242455057-i7c4ej57piivmio3os5216g4sefg6cdp.apps.googleusercontent.com
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name:
            releases/usos-srednia-${{steps.version_change.outputs.version }}.zip
          publish: true

  firefox-publish:
    runs-on: ubuntu-latest
    environment: firefox-publish
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check if version has been updated
        id: version_change
        uses: EndBug/version-check@v1

      - name: Early exit if version didn't change
        if: steps.version_change.outputs.changed != 'true'
        run: exit 1

      - name: Change manifest to V2
        # Firefox doesn't support manifest V2
        run:
          echo "`jq '.manifest_version = 2' src/manifest.json`" >
          src/manifest.json

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run release

      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{7738ac86-b5b2-4372-bc2b-1c371631bd73}'
          xpi:
            releases/usos-srednia-${{steps.version_change.outputs.version }}.zip
          manifest: dist/manifest.json
          api-key: user:16832256:680
          api-secret: ${{ secrets.CLIENT_SECRET }}
